-- Migration: Comprehensive verified places - 79 total listings
-- Run this in Supabase SQL Editor
-- Cities: London, Munich, Prague, Vienna, Berlin, Paris, Rome, Amsterdam, Barcelona, Madrid, Warsaw, Budapest, Milan

-- Step 1: Delete all existing listings
DELETE FROM public.local_listings;

-- Step 2: Insert all verified listings
INSERT INTO public.local_listings (id, source, is_active, country_code, city_slug, city_name, category, name, description, address, website_url, google_maps_url, tags, created_at)
VALUES

-- =====================
-- LONDON (5 places)
-- =====================
('e39ed74e-6a09-4e71-8f7d-bb037735e453', 'verified', true, 'GB', 'london', 'London', 'restaurant', 'Niche Gluten-free Dining', '100% Dedicated Gluten-Free restaurant', '377A St John St, London EC1V 4LD, UK', 'https://www.nichefood.co.uk', 'https://www.google.com/maps/search/?api=1&query=Niche%20Gluten-free%20Dining%20London', '["gluten free", "london", "restaurant", "dedicated"]', now()),
('a3880506-32a0-4474-88c6-776f283d6866', 'verified', true, 'GB', 'london', 'London', 'restaurant', 'Cotto', 'Italian restaurant. Celiac friendly with dedicated GF menu', '89A Westminster Bridge Rd, London SE1 7HR, UK', 'https://www.cottorestaurant.co.uk', 'https://www.google.com/maps/search/?api=1&query=Cotto%20Restaurant%20London', '["gluten free", "london", "restaurant", "italian"]', now()),
('625f3d49-3df0-4926-9c2e-8759f258377a', 'verified', true, 'GB', 'london', 'London', 'restaurant', 'Hobsons Fish & Chips Soho', '100% Dedicated Gluten-Free fish and chips', '27 St Annes Ct, London W1F 0BN, UK', 'https://www.hobsonsfishandchips.co.uk', 'https://www.google.com/maps/search/?api=1&query=Hobsons%20Fish%20Chips%20Soho%20London', '["gluten free", "london", "restaurant", "dedicated"]', now()),
('74985bb0-c746-459a-8ce7-0a3c83d37354', 'verified', true, 'GB', 'london', 'London', 'restaurant', 'Paladar', '100% Dedicated Gluten-Free Latin American restaurant', '4-5 London Rd, London SE1 6JZ, UK', 'https://www.paladar.co.uk', 'https://www.google.com/maps/search/?api=1&query=Paladar%20London', '["gluten free", "london", "restaurant", "dedicated"]', now()),
('6737259b-6d52-4df1-b6d5-3ac7b91d8c28', 'verified', true, 'GB', 'london', 'London', 'bakery', 'Libbys - Notting Hill', '100% Dedicated Gluten-Free bakery', '61a Ledbury Rd, London W11 2AA, UK', 'https://www.libbys.co.uk', 'https://www.google.com/maps/search/?api=1&query=Libbys%20Notting%20Hill%20London', '["gluten free", "london", "bakery", "dedicated"]', now()),

-- =====================
-- MUNICH (5 places)
-- =====================
('d0210afc-7b72-4643-b0a3-35b6c9f2b41d', 'verified', true, 'DE', 'munich', 'Munich', 'cafe', 'Palmtreeclub', '100% Dedicated Gluten-Free cafe', 'Augustenstraße 43, 80333 München, Germany', 'https://www.palmtreeclub.de', 'https://www.google.com/maps/search/?api=1&query=Palmtreeclub%20Munich', '["gluten free", "munich", "cafe", "dedicated"]', now()),
('fa9da594-439b-4e6e-bf6e-546552112a8d', 'verified', true, 'DE', 'munich', 'Munich', 'restaurant', 'Taverna Naxos', 'Greek restaurant with celiac-friendly options', 'Verdistraße 33, 81247 München, Germany', 'https://www.taverna-naxos.de', 'https://www.google.com/maps/search/?api=1&query=Taverna%20Naxos%20Munich', '["gluten free", "munich", "restaurant", "greek"]', now()),
('1fb4397c-1d5a-4e3b-80b9-dbd8057642a3', 'verified', true, 'DE', 'munich', 'Munich', 'restaurant', 'Wirtshaus am Bavariapark', 'Traditional German restaurant with GF options', 'Theresienhöhe 15, 80339 München, Germany', 'https://www.wirtshaus-am-bavariapark.de', 'https://www.google.com/maps/search/?api=1&query=Wirtshaus%20am%20Bavariapark%20Munich', '["gluten free", "munich", "restaurant", "german"]', now()),
('0ece1b54-6688-4624-a182-d5ca47f26f45', 'verified', true, 'DE', 'munich', 'Munich', 'restaurant', 'Bep Bu - Vietnamese Street Food', 'Vietnamese with celiac-friendly options', 'Barer Str. 48, 80799 München, Germany', 'https://www.bepbu.de', 'https://www.google.com/maps/search/?api=1&query=Bep%20Bu%20Munich', '["gluten free", "munich", "restaurant", "vietnamese"]', now()),
('5c72e107-92c7-4cfe-be98-a01d2dea0b4c', 'verified', true, 'DE', 'munich', 'Munich', 'restaurant', 'Hard Rock Cafe Munich', 'International chain with GF menu', 'Platzl 1, 80331 München, Germany', 'https://www.hardrockcafe.com/location/munich', 'https://www.google.com/maps/search/?api=1&query=Hard%20Rock%20Cafe%20Munich', '["gluten free", "munich", "restaurant"]', now()),

-- =====================
-- PRAGUE (5 places)
-- =====================
('76efb997-6183-497f-a1a8-b51e058e25aa', 'verified', true, 'CZ', 'prague', 'Prague', 'restaurant', 'Alriso Risotteria Italiana', '100% Dedicated Gluten-Free Italian restaurant', 'Betlémské nám. 11, 110 00 Praha 1, Czechia', 'https://www.alriso.cz', 'https://www.google.com/maps/search/?api=1&query=Alriso%20Risotteria%20Prague', '["gluten free", "prague", "restaurant", "dedicated", "italian"]', now()),
('b30346fb-e2f7-4902-87a9-6b6238ca719a', 'verified', true, 'CZ', 'prague', 'Prague', 'restaurant', 'Restaurace U Agamy - gluten free', '100% Dedicated Gluten-Free Czech restaurant', 'Štítného 202/35, 130 00 Praha 3, Czechia', 'https://www.uagamy.cz', 'https://www.google.com/maps/search/?api=1&query=Restaurace%20U%20Agamy%20Prague', '["gluten free", "prague", "restaurant", "dedicated", "czech"]', now()),
('9ce9ad11-9cd8-496b-8ef2-729b496e312e', 'verified', true, 'CZ', 'prague', 'Prague', 'restaurant', 'Pizza Bertoldi Jakubská', 'Pizzeria with celiac-friendly options', 'Jakubská 2, 110 00 Praha 1, Czechia', 'https://www.pizzabertoldi.cz', 'https://www.google.com/maps/search/?api=1&query=Pizza%20Bertoldi%20Prague', '["gluten free", "prague", "restaurant", "pizza"]', now()),
('e80b53a7-d7ed-4153-9d45-6d49d3908cb0', 'verified', true, 'CZ', 'prague', 'Prague', 'restaurant', 'El Centro', 'Mexican restaurant with GF options', 'Maltézské nám. 293/9, 118 00 Praha 1, Czechia', 'https://www.elcentro.cz', 'https://www.google.com/maps/search/?api=1&query=El%20Centro%20Prague', '["gluten free", "prague", "restaurant", "mexican"]', now()),
('ee1f2bf1-d709-4bb1-96b3-8034bcb3f8ec', 'verified', true, 'CZ', 'prague', 'Prague', 'bakery', 'Cukrárna Buchta', '100% Dedicated Gluten-Free bakery and confectionery', 'Národní obrany 824/35, 160 00 Praha 6, Czechia', 'https://www.cukrarnabuchta.cz', 'https://www.google.com/maps/search/?api=1&query=Cukrarna%20Buchta%20Prague', '["gluten free", "prague", "bakery", "dedicated"]', now()),

-- =====================
-- VIENNA (7 places)
-- =====================
('a1b2c3d4-1111-4aaa-8888-111111111111', 'curated', true, 'AT', 'vienna', 'Vienna', 'hospital', 'AKH Vienna – Gastroenterology', 'University hospital with expertise in celiac disease', 'Währinger Gürtel 18–20, 1090 Vienna', 'https://www.akhwien.at', 'https://www.google.com/maps/search/?api=1&query=AKH%20Vienna%20Gastroenterology', '["gluten free", "vienna", "hospital", "healthcare"]', now()),
('a1b2c3d4-2222-4aaa-8888-222222222222', 'curated', true, 'AT', 'vienna', 'Vienna', 'community', 'Austrian Coeliac Society (ÖDZ)', 'National coeliac society providing education and support', 'Vienna', 'https://www.zoeliakie.or.at', 'https://www.google.com/maps/search/?api=1&query=Austrian%20Coeliac%20Society%20Vienna', '["gluten free", "vienna", "community", "support"]', now()),
('a1b2c3d4-3333-4aaa-8888-333333333333', 'curated', true, 'AT', 'vienna', 'Vienna', 'shop', 'Billa Plus – Gluten Free Selection', 'Supermarket with dedicated gluten free ranges', 'Vienna (multiple locations)', 'https://www.billa.at', 'https://www.google.com/maps/search/?api=1&query=Billa%20Plus%20Vienna', '["gluten free", "vienna", "shop", "supermarket"]', now()),
('a1b2c3d4-4444-4aaa-8888-444444444444', 'curated', true, 'AT', 'vienna', 'Vienna', 'cafe', 'Café Ausnahmsweise', '100% Gluten free café with cakes, pastries, and meals', 'Florianigasse 16, 1080 Vienna', 'https://www.ausnahmsweise.at', 'https://www.google.com/maps/search/?api=1&query=Cafe%20Ausnahmsweise%20Vienna', '["gluten free", "vienna", "cafe", "dedicated"]', now()),
('a1b2c3d4-5555-4aaa-8888-555555555555', 'curated', true, 'AT', 'vienna', 'Vienna', 'bakery', 'Gustls Glutenfrei', 'Dedicated gluten free bakery with bread and desserts', 'Vienna', NULL, 'https://www.google.com/maps/search/?api=1&query=Gustls%20Glutenfrei%20Vienna', '["gluten free", "vienna", "bakery", "dedicated"]', now()),
('a1b2c3d4-6666-4aaa-8888-666666666666', 'curated', true, 'AT', 'vienna', 'Vienna', 'event', 'ÖDZ Vienna Regional Group', 'Regular meetups and educational events for celiacs', 'Vienna', 'https://www.zoeliakie.or.at', 'https://www.google.com/maps/search/?api=1&query=OEDZ%20Vienna', '["gluten free", "vienna", "event", "community"]', now()),
('a1b2c3d4-7777-4aaa-8888-777777777777', 'curated', true, 'AT', 'vienna', 'Vienna', 'restaurant', 'Velani', 'Gluten free restaurant with Austrian cuisine', 'Florianigasse 15, 1080 Vienna', 'https://www.velani.at', 'https://www.google.com/maps/search/?api=1&query=Velani%20Vienna', '["gluten free", "vienna", "restaurant"]', now()),

-- =====================
-- BERLIN (7 places)
-- =====================
('b1b2c3d4-1111-4bbb-9999-111111111111', 'curated', true, 'DE', 'berlin', 'Berlin', 'bakery', 'AERA Bread', '100% Dedicated gluten free sourdough bakery with café', 'Kollwitzstraße 87, 10435 Berlin', 'https://aera-bread.de', 'https://www.google.com/maps/search/?api=1&query=AERA%20Bread%20Berlin', '["gluten free", "berlin", "bakery", "dedicated"]', now()),
('b1b2c3d4-2222-4bbb-9999-222222222222', 'curated', true, 'DE', 'berlin', 'Berlin', 'hospital', 'Charité – Celiac Disease Outpatient Clinic', 'Specialized outpatient clinic for celiac disease', 'Charitéplatz 1, 10117 Berlin', 'https://www.charite.de', 'https://www.google.com/maps/search/?api=1&query=Charite%20Berlin%20Gastroenterology', '["gluten free", "berlin", "hospital", "healthcare"]', now()),
('b1b2c3d4-3333-4bbb-9999-333333333333', 'curated', true, 'DE', 'berlin', 'Berlin', 'event', 'DZG Regional Group Berlin', 'Regular meetups and educational events for celiacs', 'Berlin', 'https://www.dzg-online.de', 'https://www.google.com/maps/search/?api=1&query=DZG%20Berlin', '["gluten free", "berlin", "event", "community"]', now()),
('b1b2c3d4-4444-4bbb-9999-444444444444', 'curated', true, 'DE', 'berlin', 'Berlin', 'community', 'German Coeliac Society (DZG)', 'National coeliac society HQ with education and certification', 'Bundesallee 218, 10719 Berlin', 'https://www.dzg-online.de', 'https://www.google.com/maps/search/?api=1&query=DZG%20German%20Coeliac%20Society%20Berlin', '["gluten free", "berlin", "community", "support"]', now()),
('b1b2c3d4-5555-4bbb-9999-555555555555', 'curated', true, 'DE', 'berlin', 'Berlin', 'shop', 'Glutenfreie Welt', 'Specialty shop with certified gluten free products', 'Berlin (multiple locations)', 'https://www.glutenfreie-welt.de', 'https://www.google.com/maps/search/?api=1&query=Glutenfreie%20Welt%20Berlin', '["gluten free", "berlin", "shop"]', now()),
('b1b2c3d4-6666-4bbb-9999-666666666666', 'curated', true, 'DE', 'berlin', 'Berlin', 'bakery', 'Jute Bäckerei', 'Dedicated gluten free bakery with bread, pastries, cakes', 'Schönhauser Allee 102, 10439 Berlin', 'https://www.jute-baeckerei.de', 'https://www.google.com/maps/search/?api=1&query=Jute%20Backerei%20Berlin', '["gluten free", "berlin", "bakery", "dedicated"]', now()),
('b1b2c3d4-7777-4bbb-9999-777777777777', 'curated', true, 'DE', 'berlin', 'Berlin', 'restaurant', 'Velicious', 'Vegan and gluten free friendly café and restaurant', 'Danziger Str. 33, 10435 Berlin', 'https://velicious.de', 'https://www.google.com/maps/search/?api=1&query=Velicious%20Berlin', '["gluten free", "berlin", "restaurant", "vegan"]', now()),

-- =====================
-- PARIS (10 places) - NEW
-- =====================
('c1c1c1c1-1111-4ccc-aaaa-111111111111', 'verified', true, 'FR', 'paris', 'Paris', 'restaurant', 'Little Nonna', '100% Dedicated Gluten-Free Italian pizzeria with wood-fired pizza, pasta, and tiramisu', 'Paris (near Arc de Triomphe)', 'https://www.littlenonna.fr', 'https://www.google.com/maps/search/?api=1&query=Little%20Nonna%20Paris', '["gluten free", "paris", "restaurant", "dedicated", "italian", "pizza"]', now()),
('c1c1c1c1-2222-4ccc-aaaa-222222222222', 'verified', true, 'FR', 'paris', 'Paris', 'restaurant', 'Tasca', '100% Dedicated Gluten-Free Italian trattoria near Eiffel Tower', 'Paris (near Eiffel Tower)', 'https://www.tasca-paris.fr', 'https://www.google.com/maps/search/?api=1&query=Tasca%20Paris%20Gluten%20Free', '["gluten free", "paris", "restaurant", "dedicated", "italian"]', now()),
('c1c1c1c1-3333-4ccc-aaaa-333333333333', 'verified', true, 'FR', 'paris', 'Paris', 'cafe', 'Café Mareva', '100% Gluten-free and dairy-free brunch café in Montmartre', 'Montmartre, Paris', 'https://www.cafemareva.fr', 'https://www.google.com/maps/search/?api=1&query=Cafe%20Mareva%20Paris', '["gluten free", "paris", "cafe", "dedicated", "brunch"]', now()),
('c1c1c1c1-4444-4ccc-aaaa-444444444444', 'verified', true, 'FR', 'paris', 'Paris', 'bakery', 'La Manufacture du Sans Gluten', '100% Dedicated GF bakery - award-winning croissants and pastries', '2 Rue Androuet, 75018 Paris (Montmartre)', 'https://www.lamanufacturedusansgluten.com', 'https://www.google.com/maps/search/?api=1&query=La%20Manufacture%20du%20Sans%20Gluten%20Paris', '["gluten free", "paris", "bakery", "dedicated"]', now()),
('c1c1c1c1-5555-4ccc-aaaa-555555555555', 'verified', true, 'FR', 'paris', 'Paris', 'bakery', 'Chambelland Boulangerie', '100% Gluten-free bakery with rice/buckwheat breads and éclairs', '43 Rue Brochant, 75017 Paris', 'https://www.chambelland.com', 'https://www.google.com/maps/search/?api=1&query=Chambelland%20Boulangerie%20Paris', '["gluten free", "paris", "bakery", "dedicated"]', now()),
('c1c1c1c1-6666-4ccc-aaaa-666666666666', 'verified', true, 'FR', 'paris', 'Paris', 'bakery', 'Copains', '100% Gluten-free bakery with breads, pastries, babka', 'Paris (multiple locations)', 'https://www.copains-paris.fr', 'https://www.google.com/maps/search/?api=1&query=Copains%20Gluten%20Free%20Paris', '["gluten free", "paris", "bakery", "dedicated"]', now()),
('c1c1c1c1-7777-4ccc-aaaa-777777777777', 'verified', true, 'FR', 'paris', 'Paris', 'bakery', 'Helmut Newcake', '100% Dedicated GF bakery with classic French pastries', 'Central Paris', 'https://www.helmutnewcake.com', 'https://www.google.com/maps/search/?api=1&query=Helmut%20Newcake%20Paris', '["gluten free", "paris", "bakery", "dedicated"]', now()),
('c1c1c1c1-8888-4ccc-aaaa-888888888888', 'verified', true, 'FR', 'paris', 'Paris', 'bakery', 'Maison Plume', 'Gluten-free and sugar-free pastries and cheesecakes', '61 Rue Charlot, 75003 Paris (Le Marais)', 'https://www.maisonplume.fr', 'https://www.google.com/maps/search/?api=1&query=Maison%20Plume%20Paris', '["gluten free", "paris", "bakery", "dedicated"]', now()),
('c1c1c1c1-9999-4ccc-aaaa-999999999999', 'verified', true, 'FR', 'paris', 'Paris', 'bakery', 'Noglu', '100% Gluten-free bakery with pastries, baguettes, doughnuts', '62 Rue de Vaugirard, 75006 Paris', 'https://www.noglu.fr', 'https://www.google.com/maps/search/?api=1&query=Noglu%20Paris', '["gluten free", "paris", "bakery", "dedicated"]', now()),
('c1c1c1c1-aaaa-4ccc-aaaa-aaaaaaaaaaaa', 'verified', true, 'FR', 'paris', 'Paris', 'community', 'AFDIAG - French Coeliac Association', 'French national coeliac association for support and resources', 'Paris', 'https://www.afdiag.fr', 'https://www.google.com/maps/search/?api=1&query=AFDIAG%20Paris', '["gluten free", "paris", "community", "support"]', now()),

-- =====================
-- ROME (8 places) - NEW
-- =====================
('d1d1d1d1-1111-4ddd-bbbb-111111111111', 'verified', true, 'IT', 'rome', 'Rome', 'restaurant', 'Mama Eat', '100% Dedicated Gluten-Free restaurant with pizzas and pasta', 'Rome (Centro Storico)', 'https://www.mamaeat.it', 'https://www.google.com/maps/search/?api=1&query=Mama%20Eat%20Rome', '["gluten free", "rome", "restaurant", "dedicated", "pizza"]', now()),
('d1d1d1d1-2222-4ddd-bbbb-222222222222', 'verified', true, 'IT', 'rome', 'Rome', 'bakery', 'Pandalì', '100% Dedicated GF bakery and casual eatery in Centro Storico', 'Centro Storico, Rome', 'https://www.pandali.it', 'https://www.google.com/maps/search/?api=1&query=Pandali%20Rome', '["gluten free", "rome", "bakery", "dedicated"]', now()),
('d1d1d1d1-3333-4ddd-bbbb-333333333333', 'verified', true, 'IT', 'rome', 'Rome', 'cafe', 'Gelateria Fatamorgana', '100% Gluten-free gelato with 8 locations in Rome', 'Rome (multiple locations)', 'https://www.fatamorganagelateria.it', 'https://www.google.com/maps/search/?api=1&query=Fatamorgana%20Gelato%20Rome', '["gluten free", "rome", "cafe", "dedicated", "gelato"]', now()),
('d1d1d1d1-4444-4ddd-bbbb-444444444444', 'verified', true, 'IT', 'rome', 'Rome', 'bakery', 'New Food Ponte Sisto Gluten Free', '100% Dedicated GF bakery with pastries and croissants', 'Near Ponte Sisto, Rome', NULL, 'https://www.google.com/maps/search/?api=1&query=New%20Food%20Ponte%20Sisto%20Rome', '["gluten free", "rome", "bakery", "dedicated"]', now()),
('d1d1d1d1-5555-4ddd-bbbb-555555555555', 'verified', true, 'IT', 'rome', 'Rome', 'restaurant', 'La Soffitta Renovatio', 'AIC-certified restaurant near Vatican', 'Piazza del Risorgimento, 46/a, Rome', NULL, 'https://www.google.com/maps/search/?api=1&query=La%20Soffitta%20Renovatio%20Rome', '["gluten free", "rome", "restaurant", "certified"]', now()),
('d1d1d1d1-6666-4ddd-bbbb-666666666666', 'verified', true, 'IT', 'rome', 'Rome', 'restaurant', 'Pantha Rei', 'AIC-certified restaurant near Pantheon', 'Via della Minerva, 19, Rome', NULL, 'https://www.google.com/maps/search/?api=1&query=Pantha%20Rei%20Rome', '["gluten free", "rome", "restaurant", "certified"]', now()),
('d1d1d1d1-7777-4ddd-bbbb-777777777777', 'verified', true, 'IT', 'rome', 'Rome', 'restaurant', 'Voglia di Pizza', 'AIC-certified pizzeria near Pantheon', 'Near Pantheon, Rome', NULL, 'https://www.google.com/maps/search/?api=1&query=Voglia%20di%20Pizza%20Rome', '["gluten free", "rome", "restaurant", "pizza", "certified"]', now()),
('d1d1d1d1-8888-4ddd-bbbb-888888888888', 'verified', true, 'IT', 'rome', 'Rome', 'community', 'AIC - Italian Coeliac Association', 'Italian national coeliac association with certification program', 'Rome', 'https://www.celiachia.it', 'https://www.google.com/maps/search/?api=1&query=AIC%20Rome', '["gluten free", "rome", "community", "support"]', now()),

-- =====================
-- AMSTERDAM (5 places) - NEW
-- =====================
('e1e1e1e1-1111-4eee-cccc-111111111111', 'verified', true, 'NL', 'amsterdam', 'Amsterdam', 'restaurant', 'Croque Madame Gluten Free Food', '100% Dedicated GF café near Centraal Station', 'Sint Annendwarsstraat 24A, 1012HC Amsterdam', NULL, 'https://www.google.com/maps/search/?api=1&query=Croque%20Madame%20Amsterdam', '["gluten free", "amsterdam", "restaurant", "dedicated"]', now()),
('e1e1e1e1-2222-4eee-cccc-222222222222', 'verified', true, 'NL', 'amsterdam', 'Amsterdam', 'bakery', 'Rose and Vanilla', '100% Dedicated gluten-free bakery', 'Eerste Constantijn Huygensstraat 74, Amsterdam', NULL, 'https://www.google.com/maps/search/?api=1&query=Rose%20and%20Vanilla%20Amsterdam', '["gluten free", "amsterdam", "bakery", "dedicated"]', now()),
('e1e1e1e1-3333-4eee-cccc-333333333333', 'verified', true, 'NL', 'amsterdam', 'Amsterdam', 'restaurant', 'Omelegg – Omeletterie', 'Omelette restaurant with gluten-free options at multiple locations', 'Amsterdam (City Centre, De Pijp, Jordaan)', 'https://www.omelegg.com', 'https://www.google.com/maps/search/?api=1&query=Omelegg%20Amsterdam', '["gluten free", "amsterdam", "restaurant", "breakfast"]', now()),
('e1e1e1e1-4444-4eee-cccc-444444444444', 'verified', true, 'NL', 'amsterdam', 'Amsterdam', 'community', 'Nederlandse Coeliakie Vereniging', 'Dutch Coeliac Association for support and resources', 'Netherlands', 'https://www.glutenvrij.nl', 'https://www.google.com/maps/search/?api=1&query=NCV%20Netherlands', '["gluten free", "amsterdam", "community", "support"]', now()),
('e1e1e1e1-5555-4eee-cccc-555555555555', 'verified', true, 'NL', 'amsterdam', 'Amsterdam', 'shop', 'Albert Heijn - Gluten Free Selection', 'Major supermarket chain with GF product range', 'Amsterdam (multiple locations)', 'https://www.ah.nl', 'https://www.google.com/maps/search/?api=1&query=Albert%20Heijn%20Amsterdam', '["gluten free", "amsterdam", "shop", "supermarket"]', now()),

-- =====================
-- BARCELONA (7 places) - NEW
-- =====================
('f1f1f1f1-1111-4fff-dddd-111111111111', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'restaurant', 'Messié Sin Gluten Muntaner', '100% Dedicated GF pizzeria certified by Catalan coeliac society', 'Carrer de Muntaner, 109, 08036 Barcelona', 'https://www.messie.es', 'https://www.google.com/maps/search/?api=1&query=Messie%20Sin%20Gluten%20Muntaner%20Barcelona', '["gluten free", "barcelona", "restaurant", "dedicated", "pizza"]', now()),
('f1f1f1f1-2222-4fff-dddd-222222222222', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'restaurant', 'Messié Pizza Gluten Free Gràcia', '100% Dedicated GF pizzeria in Gràcia', 'Carrer de Siracusa, 15, 08012 Barcelona', 'https://www.messie.es', 'https://www.google.com/maps/search/?api=1&query=Messie%20Gracia%20Barcelona', '["gluten free", "barcelona", "restaurant", "dedicated", "pizza"]', now()),
('f1f1f1f1-3333-4fff-dddd-333333333333', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'restaurant', 'Pötstot', '100% Dedicated GF and vegan Spanish restaurant with tapas', 'Barcelona (west of Passeig de Gràcia)', 'https://www.potstot.com', 'https://www.google.com/maps/search/?api=1&query=Potstot%20Barcelona', '["gluten free", "barcelona", "restaurant", "dedicated", "vegan", "tapas"]', now()),
('f1f1f1f1-4444-4fff-dddd-444444444444', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'restaurant', 'En Ville', '100% GF Catalan cuisine certified by coeliac society', 'Barcelona', 'https://www.envillebarcelona.es', 'https://www.google.com/maps/search/?api=1&query=En%20Ville%20Barcelona', '["gluten free", "barcelona", "restaurant", "dedicated", "catalan"]', now()),
('f1f1f1f1-5555-4fff-dddd-555555555555', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'restaurant', 'Grosso Napolitano (GF Location)', '100% Dedicated GF pizza location', 'Barcelona (verify GF location)', 'https://www.grossonapolitano.com', 'https://www.google.com/maps/search/?api=1&query=Grosso%20Napolitano%20Barcelona', '["gluten free", "barcelona", "restaurant", "dedicated", "pizza"]', now()),
('f1f1f1f1-6666-4fff-dddd-666666666666', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'cafe', 'Manduka Café', '100% Dedicated GF brunch café in Born neighborhood', 'Born, Barcelona', 'https://www.mandukacafe.com', 'https://www.google.com/maps/search/?api=1&query=Manduka%20Cafe%20Barcelona', '["gluten free", "barcelona", "cafe", "dedicated", "brunch"]', now()),
('f1f1f1f1-7777-4fff-dddd-777777777777', 'verified', true, 'ES', 'barcelona', 'Barcelona', 'community', 'SMAP - Catalan Coeliac Association', 'Catalan coeliac association for certification and support', 'Barcelona', 'https://www.celiacscatalunya.org', 'https://www.google.com/maps/search/?api=1&query=SMAP%20Barcelona', '["gluten free", "barcelona", "community", "support"]', now()),

-- =====================
-- MADRID (7 places) - NEW
-- =====================
('g1g1g1g1-1111-4ggg-eeee-111111111111', 'verified', true, 'ES', 'madrid', 'Madrid', 'restaurant', 'Pizza Natura', '100% Dedicated GF pizzeria with desserts and salads', 'C. de Jovellanos, 6, 28014 Madrid', 'https://www.pizzanatura.es', 'https://www.google.com/maps/search/?api=1&query=Pizza%20Natura%20Madrid', '["gluten free", "madrid", "restaurant", "dedicated", "pizza"]', now()),
('g1g1g1g1-2222-4ggg-eeee-222222222222', 'verified', true, 'ES', 'madrid', 'Madrid', 'restaurant', 'Pinks (GF Location)', '100% Dedicated GF burger restaurant', 'Calle de Viriato, 68, 28010 Madrid', 'https://www.pinksburgers.com', 'https://www.google.com/maps/search/?api=1&query=Pinks%20Viriato%20Madrid', '["gluten free", "madrid", "restaurant", "dedicated", "burgers"]', now()),
('g1g1g1g1-3333-4ggg-eeee-333333333333', 'verified', true, 'ES', 'madrid', 'Madrid', 'restaurant', 'As De Bastos Madrid', '100% Dedicated GF Spanish tapas and grilled dishes', 'Calle de Castilla, 62, 28039 Madrid', 'https://www.asdebastos.es', 'https://www.google.com/maps/search/?api=1&query=As%20De%20Bastos%20Madrid', '["gluten free", "madrid", "restaurant", "dedicated", "tapas"]', now()),
('g1g1g1g1-4444-4ggg-eeee-444444444444', 'verified', true, 'ES', 'madrid', 'Madrid', 'restaurant', 'Restaurante Vegetariano Artemisa', '100% GF and vegetarian since 2016', 'C. de Ventura de la Vega, 4, 28014 Madrid', 'https://www.restauranteartemisa.com', 'https://www.google.com/maps/search/?api=1&query=Artemisa%20Madrid', '["gluten free", "madrid", "restaurant", "dedicated", "vegetarian"]', now()),
('g1g1g1g1-5555-4ggg-eeee-555555555555', 'verified', true, 'ES', 'madrid', 'Madrid', 'restaurant', 'LaLina', '100% Dedicated GF tapas with creative dishes', 'Calle de Echegaray, 5, 28014 Madrid', 'https://www.lalina.es', 'https://www.google.com/maps/search/?api=1&query=LaLina%20Madrid', '["gluten free", "madrid", "restaurant", "dedicated", "tapas"]', now()),
('g1g1g1g1-6666-4ggg-eeee-666666666666', 'verified', true, 'ES', 'madrid', 'Madrid', 'bakery', 'Pastelería La Oriental', '100% Dedicated GF bakery with pastries', 'C. de Ferraz, 47, 28008 Madrid', NULL, 'https://www.google.com/maps/search/?api=1&query=Pasteleria%20La%20Oriental%20Madrid', '["gluten free", "madrid", "bakery", "dedicated"]', now()),
('g1g1g1g1-7777-4ggg-eeee-777777777777', 'verified', true, 'ES', 'madrid', 'Madrid', 'community', 'FACE - Spanish Coeliac Federation', 'Spanish national coeliac federation', 'Madrid', 'https://www.celiacos.org', 'https://www.google.com/maps/search/?api=1&query=FACE%20Madrid', '["gluten free", "madrid", "community", "support"]', now()),

-- =====================
-- WARSAW (5 places) - NEW
-- =====================
('h1h1h1h1-1111-4hhh-ffff-111111111111', 'verified', true, 'PL', 'warsaw', 'Warsaw', 'restaurant', 'Królowa Bezglutenowa', '100% Dedicated GF bistro certified by Polish Celiac Society', 'Radzymińska 150, 03-574 Warszawa', NULL, 'https://www.google.com/maps/search/?api=1&query=Krolowa%20Bezglutenowa%20Warsaw', '["gluten free", "warsaw", "restaurant", "dedicated", "certified"]', now()),
('h1h1h1h1-2222-4hhh-ffff-222222222222', 'verified', true, 'PL', 'warsaw', 'Warsaw', 'restaurant', 'Wiesz co Zjesz', '100% Dedicated GF Polish and Mediterranean dishes', 'Warsaw', NULL, 'https://www.google.com/maps/search/?api=1&query=Wiesz%20co%20Zjesz%20Warsaw', '["gluten free", "warsaw", "restaurant", "dedicated", "polish"]', now()),
('h1h1h1h1-3333-4hhh-ffff-333333333333', 'verified', true, 'PL', 'warsaw', 'Warsaw', 'restaurant', 'Zapiecek', 'Traditional Polish with certified GF pierogi', 'Piwna 34/36, 00-256 Warszawa', 'https://www.zapiecek.eu', 'https://www.google.com/maps/search/?api=1&query=Zapiecek%20Warsaw', '["gluten free", "warsaw", "restaurant", "polish", "pierogi"]', now()),
('h1h1h1h1-4444-4hhh-ffff-444444444444', 'verified', true, 'PL', 'warsaw', 'Warsaw', 'restaurant', 'The Chef House', 'Accredited GF burgers, pizza, pasta', 'Obrzeżna 3, 02-691 Warszawa', NULL, 'https://www.google.com/maps/search/?api=1&query=The%20Chef%20House%20Warsaw', '["gluten free", "warsaw", "restaurant", "certified"]', now()),
('h1h1h1h1-5555-4hhh-ffff-555555555555', 'verified', true, 'PL', 'warsaw', 'Warsaw', 'community', 'Polskie Stowarzyszenie Osób z Celiakią', 'Polish Celiac Society for certification and support', 'Warsaw', 'https://www.celiakia.pl', 'https://www.google.com/maps/search/?api=1&query=Polish%20Celiac%20Society', '["gluten free", "warsaw", "community", "support"]', now()),

-- =====================
-- BUDAPEST (6 places) - NEW
-- =====================
('i1i1i1i1-1111-4iii-gggg-111111111111', 'verified', true, 'HU', 'budapest', 'Budapest', 'restaurant', 'Bohemtanya Gluténmentes Vendéglő', '100% Dedicated GF Hungarian restaurant with goulash and paprikash', 'Central Pest, Budapest', NULL, 'https://www.google.com/maps/search/?api=1&query=Bohemtanya%20Budapest', '["gluten free", "budapest", "restaurant", "dedicated", "hungarian"]', now()),
('i1i1i1i1-2222-4iii-gggg-222222222222', 'verified', true, 'HU', 'budapest', 'Budapest', 'cafe', 'Cöli Bisztró', '100% Dedicated GF bakery, café and bistro', 'Jókai u. 40, 1066 Budapest', NULL, 'https://www.google.com/maps/search/?api=1&query=Coli%20Bisztro%20Budapest', '["gluten free", "budapest", "cafe", "dedicated", "bakery"]', now()),
('i1i1i1i1-3333-4iii-gggg-333333333333', 'verified', true, 'HU', 'budapest', 'Budapest', 'restaurant', 'Kata Restaurant', '100% Dedicated GF upscale Hungarian cuisine', 'Central Budapest', NULL, 'https://www.google.com/maps/search/?api=1&query=Kata%20Restaurant%20Budapest', '["gluten free", "budapest", "restaurant", "dedicated", "hungarian"]', now()),
('i1i1i1i1-4444-4iii-gggg-444444444444', 'verified', true, 'HU', 'budapest', 'Budapest', 'restaurant', 'Drumf Bistro', '100% Dedicated GF, lactose-free, sugar-free options', 'Budapest', NULL, 'https://www.google.com/maps/search/?api=1&query=Drumf%20Bistro%20Budapest', '["gluten free", "budapest", "restaurant", "dedicated"]', now()),
('i1i1i1i1-5555-4iii-gggg-555555555555', 'verified', true, 'HU', 'budapest', 'Budapest', 'restaurant', 'Monkeys', '100% Dedicated GF with gluten-free beers', 'Budapest', NULL, 'https://www.google.com/maps/search/?api=1&query=Monkeys%20Budapest', '["gluten free", "budapest", "restaurant", "dedicated"]', now()),
('i1i1i1i1-6666-4iii-gggg-666666666666', 'verified', true, 'HU', 'budapest', 'Budapest', 'community', 'Lisztérzékenyek Érdekvédelmi Egyesülete', 'Hungarian Coeliac Society for support and resources', 'Budapest', 'https://www.coeliac.hu', 'https://www.google.com/maps/search/?api=1&query=Hungarian%20Coeliac%20Society', '["gluten free", "budapest", "community", "support"]', now()),

-- =====================
-- MILAN (6 places) - NEW
-- =====================
('j1j1j1j1-1111-4jjj-hhhh-111111111111', 'verified', true, 'IT', 'milan', 'Milan', 'restaurant', 'Bistrò (Milan)', '100% Dedicated GF Italian and French cuisine', 'Between Sant Ambrogio and Duomo, Milan', NULL, 'https://www.google.com/maps/search/?api=1&query=Bistro%20Gluten%20Free%20Milan', '["gluten free", "milan", "restaurant", "dedicated"]', now()),
('j1j1j1j1-2222-4jjj-hhhh-222222222222', 'verified', true, 'IT', 'milan', 'Milan', 'restaurant', 'Risotteria Melotti Milan', '100% Dedicated GF risotto restaurant', 'Milan', 'https://www.risotteriamelotti.it', 'https://www.google.com/maps/search/?api=1&query=Risotteria%20Melotti%20Milan', '["gluten free", "milan", "restaurant", "dedicated", "risotto"]', now()),
('j1j1j1j1-3333-4jjj-hhhh-333333333333', 'verified', true, 'IT', 'milan', 'Milan', 'bakery', 'PanPerMe', '100% Dedicated GF bakery with focaccia and pizza', 'Near Duomo, Milan', NULL, 'https://www.google.com/maps/search/?api=1&query=PanPerMe%20Milan', '["gluten free", "milan", "bakery", "dedicated"]', now()),
('j1j1j1j1-4444-4jjj-hhhh-444444444444', 'verified', true, 'IT', 'milan', 'Milan', 'bakery', 'Via Dalla Spiga', '100% Dedicated GF bakery with pastries and focaccia', 'West Milan (near Last Supper)', NULL, 'https://www.google.com/maps/search/?api=1&query=Via%20Dalla%20Spiga%20Milan', '["gluten free", "milan", "bakery", "dedicated"]', now()),
('j1j1j1j1-5555-4jjj-hhhh-555555555555', 'verified', true, 'IT', 'milan', 'Milan', 'cafe', 'Out of the Box Gelato', '100% Dedicated GF gelato shop', 'Milan (Milano Centrale and Porta Romana)', NULL, 'https://www.google.com/maps/search/?api=1&query=Out%20of%20the%20Box%20Gelato%20Milan', '["gluten free", "milan", "cafe", "dedicated", "gelato"]', now()),
('j1j1j1j1-6666-4jjj-hhhh-666666666666', 'verified', true, 'IT', 'milan', 'Milan', 'bakery', 'Pasticceria Navotti Senza Glutine', 'AIC-accredited GF bakery', 'Milan', NULL, 'https://www.google.com/maps/search/?api=1&query=Pasticceria%20Navotti%20Milan', '["gluten free", "milan", "bakery", "certified"]', now());
